version: "3.3"
services:
  xray:
    image: "mboxjem/xray-dynamic-path:latest"
    configs:
      - source: "xray_config"
        target: "/etc/xray/config.json"
    networks:
      - "kuma_network"
    deploy:
      restart_policy:
        condition: "on-failure"
      replicas: 2
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    configs:
      - source: "nginx_config"
        target: "/etc/nginx/conf.d/default.conf"
      - source: "html_config"
        target: "/usr/share/nginx/html/index.html"
    depends_on:
      - "xray"
    networks:
      - "kuma_network"
    deploy:
      restart_policy:
        condition: "on-failure"
      replicas: 1
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    command: "tunnel run"
    depends_on:
      - "xray"
      - "nginx"
    networks:
      - "kuma_network"
    deploy:
      restart_policy:
        condition: "on-failure"
      replicas: 1

networks:
    kuma_network:
       driver: "overlay"

configs:
  xray_config:
    file: "./xray/config.json"
  nginx_config:
    file: "./nginx/default.conf"
  html_config:
    file: "./nginx/index.html"