version: "3"
services:
  xray:
    image: "mboxjem/xray-dynamic-path:latest"
    container_name: "xray"
    expose:
      - "10000"
    volumes:
      - "xray_config:/etc/xray/config.json"
    restart: "unless-stopped"
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - "nginx_config:/etc/nginx/conf.d/default.conf"
      - "html_config:/usr/share/nginx/html/index.html"
    depends_on:
      - "xray"
    restart: "unless-stopped"
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflared"
    command: "tunnel run"
    depends_on:
      - "xray"
      - "nginx"
    restart: "unless-stopped"

configs:
  xray_config:
    file: "./xray/config.json"
  nginx_config:
    file: "./nginx/default.conf"
  html_config:
    file: "./nginx/index.html"