version: "3.3"
services:
  xray:
    image: "xray-dynamic-path:latest"
    configs:
      - source: "xray_config"
        target: "/etc/xray/config.json"
    environment:
      TZ: "Asia/Jakarta"
    networks:
      - "kuma_network"
    deploy:
      restart_policy:
        condition: "on-failure"
      replicas: 2
  nginx:
    image: "openresty/openresty:alpine"
    ports:
      - "80:80"
    configs:
      - source: "nginx_config"
        target: "/etc/nginx/conf.d/default.conf"
    depends_on:
      - "xray"
    networks:
      - "kuma_network"
    deploy:
      restart_policy:
        condition: "on-failure"
      replicas: 2

networks:
    kuma_network:
       driver: "overlay"

configs:
  xray_config:
    file: "./xray/config.json"
  nginx_config:
    file: "./nginx/default.conf"