version: "3"
services:
  xray:
    build: "."
    container_name: "xray"
    expose:
      - "10000"
    volumes:
      - "./xray/config.json:/etc/xray/config.json"
    restart: "unless-stopped"
  openresty:
    image: "openresty/openresty:alpine"
    container_name: "openresty"
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "xray"
    restart: "unless-stopped"